version: '3'
services:
  pgdb:
    image: postgres:16-alpine
    container_name: database
    volumes:
      - pgdata:/var/lib/podtgresql/data
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  server:
    build:
      context: ./server/
      dockerfile: Dockerfile
    container_name: lead_server
    depends_on:
      - adminer
    ports:
      - 5000:5000
    volumes:
      - ./server:/code
    command: uvicorn main:app --host 0.0.0.0 --port 5000 --reload


  client:
    build:
      context: ./client/
    container_name: lead_client
    depends_on:
      - adminer
    volumes:
      - ./client:/code
      - node_modules:/app/node_modules/
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=development

volumes:
  pgdata:
  node_modules:

